config/routes.rb
Rails.application.routes.draw do
  resources :habits
  devise_for :users


  root 'pages#index'
  get 'pages/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/habit.rb
class Habit < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :habits, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/habits_controller.rb
class HabitsController < ApplicationController
  before_action :set_habit, only: [:show, :edit, :update, :destroy]

  def index
    authenticate_user!

    @habits = Habit.all
  end

  def show
  end

  def new
    authenticate_user!

    @habit = Habit.new
  end

  def edit
  end

  def create
    authenticate_user!

    @habit = Habit.new(habit_params)
    @habit.user = current_user

    if @habit.save
      redirect_to @habit, notice: 'Habit was successfully created.'
    else
      render :new
    end
  end

  def update
    authenticate_user!

    if @habit.update(habit_params)
      redirect_to @habit, notice: 'Habit was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    authenticate_user!

    @habit.destroy
    redirect_to habits_url, notice: 'Habit was successfully destroyed.'
  end

  private

  def set_habit
    @habit = Habit.find(params[:id])
  end

  def habit_params
    params.require(:habit).permit(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/habits_helper.rb
module HabitsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/habits/_form.html.erb
<%= form_with(model: habit, local: true) do |form| %>
  <% if habit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(habit.errors.count, "error") %> prohibited this habit from being saved:</h2>

      <ul>
        <% habit.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/habits/edit.html.erb
<h1>Edit Habit</h1>

<%= render 'form', habit: @habit %>

<%= link_to 'Back', habits_path %>

app/views/habits/index.html.erb
<h1>Habits</h1>

<%= link_to 'New Habit', new_habit_path %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @habits.each do |habit| %>
      <tr>
        <td><%= habit.name %></td>
        <td><%= link_to 'Show', habit %></td>
        <td><%= link_to 'Edit', edit_habit_path(habit) %></td>
        <td><%= link_to 'Destroy', habit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/habits/new.html.erb
<h1>New Habit</h1>

<%= render 'form', habit: @habit %>

<%= link_to 'Back', habits_path %>

app/views/habits/show.html.erb
<h1>Habit: <%= @habit.name %></h1>

<p>
  <strong>Name:</strong>
  <%= @habit.name %>
</p>

<%= link_to 'Edit', edit_habit_path(@habit) %> |
<%= link_to 'Back', habits_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Monumental Habits</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@200..800&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="h-screen p-0 m-0">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<div>
  <% if user_signed_in? %>
    <h1>Welcome Home, <%= current_user.email %></h1>
    <%= link_to 'Sign out', destroy_user_session_path, data: { turbo_method: :delete } %>
  <% else %>
    <h1 class="text-morning font-klasik capitalize">Welcome</h1>
    <%= link_to 'Sign in', new_user_session_path %>
  <% end %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <span>Já tem um conta? <%= link_to "Entrar", new_session_path(resource_name), class: "font-bold" %></span>
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Esqueceu a senha?", new_password_path(resource_name), class: "underline underline-offset-1" %>
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <span class="text-eclipse">Não tem conta? <%= link_to " Crie aqui", new_registration_path(resource_name), class: "font-bold" %></span>
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>